services:
  db:
    image: postgres:15-alpine
    container_name: lab2_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: links_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d links_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: lab2_webapp
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/links_db
      SECRET_KEY: supersecretkeychangeinprod
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: